name: flutter_uaal_niantic_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  package_rename:

flutter:
  uses-material-design: true

package_rename_config:
  android:
    app_name: "UaaL Niantic Sample" # 画面に出るアプリ名
    package_name: "com.stak4.flutteruaalnianticsample" # 変えたいパッケージ名

  ios:
    app_name: "UaaL Niantic Sample"
    bundle_name: "UaaLNianticSample"
    package_name: "com.stak4.flutteruaalnianticsample"
