name: flutter_uaal_niantic_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  package_rename:

flutter:
  uses-material-design: true

package_rename_config:
  android:
    app_name: "UaaL Niantic Sample" # 画面に出るアプリ名
    package_name: "com.stak4.flutteruaalnianticsample" # 変えたいパッケージ名

  ios:
    app_name: "UaaL Niantic Sample"
    bundle_name: "UaaLNianticSample"
    package_name: "com.stak4.flutteruaalnianticsample"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/icon.png"
  adaptive_icon_foreground_inset: 4
